package auctionPack;


/**
* auction/AuctionPackage/AuctionStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

public final class AuctionStatus implements org.omg.CORBA.portable.IDLEntity
{
  public String user = null;
  public String item = null;
  public float currentPrice = (float)0;

  public AuctionStatus ()
  {
  } // ctor

  public AuctionStatus (String _user, String _item, float _currentPrice)
  {
    user = _user;
    item = _item;
    currentPrice = _currentPrice;
  } // ctor

} // class AuctionStatus
