package auctionPack;


/**
* auction/AuctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

public interface AuctionOperations 
{

  // seller accessible methods
  boolean offer (String sellerId, String item, float initPrice) throws auctionPack.InvalidOfferException;
  boolean sell (String itemName) throws auctionPack.InvalidSellException;
  String viewHighBidder (String itemName) throws auctionPack.InvalidSellException;

  // bidder accessible methods
  boolean bid (String userId, float bidPrice) throws auctionPack.InvalidBidException;
  String viewBidStatus (String userId) throws auctionPack.InvalidBidException;

  // universally accessible methods
  auctionPack.AuctionStatus viewAuctionStatus () throws auctionPack.InvalidStatusException;
} // interface AuctionOperations
