package auctionPack;


/**
* auction/AuctionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

abstract public class AuctionHelper
{
  private static final String  _id = "IDL:auction/Auction:1.0";

  public static void insert (org.omg.CORBA.Any a, auctionPack.Auction that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static auctionPack.Auction extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (auctionPack.AuctionHelper.id (), "Auction");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static auctionPack.Auction read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AuctionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, auctionPack.Auction value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static auctionPack.Auction narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof auctionPack.Auction)
      return (auctionPack.Auction)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
            auctionPack._AuctionStub stub = new auctionPack._AuctionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static auctionPack.Auction unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof auctionPack.Auction)
      return (auctionPack.Auction)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
            auctionPack._AuctionStub stub = new auctionPack._AuctionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
