package auctionPack;


/**
* auction/AuctionPackage/InvalidStatusException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

public final class InvalidStatusException extends org.omg.CORBA.UserException
{
  public String description = null;

  public InvalidStatusException ()
  {
    super(InvalidStatusExceptionHelper.id());
  } // ctor

  public InvalidStatusException (String _description)
  {
    super(InvalidStatusExceptionHelper.id());
    description = _description;
  } // ctor


  public InvalidStatusException (String $reason, String _description)
  {
    super(InvalidStatusExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class InvalidStatusException
