package auctionPack;


/**
* auction/AuctionPackage/InvalidBidException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

public final class InvalidBidException extends org.omg.CORBA.UserException
{
  public String description = null;

  public InvalidBidException ()
  {
    super(InvalidBidExceptionHelper.id());
  } // ctor

  public InvalidBidException (String _description)
  {
    super(InvalidBidExceptionHelper.id());
    description = _description;
  } // ctor


  public InvalidBidException (String $reason, String _description)
  {
    super(InvalidBidExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class InvalidBidException
