package auctionPack;


/**
* auction/AuctionPackage/InvalidOfferException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

public final class InvalidOfferException extends org.omg.CORBA.UserException
{
  public String description = null;

  public InvalidOfferException ()
  {
    super(InvalidOfferExceptionHelper.id());
  } // ctor

  public InvalidOfferException (String _description)
  {
    super(InvalidOfferExceptionHelper.id());
    description = _description;
  } // ctor


  public InvalidOfferException (String $reason, String _description)
  {
    super(InvalidOfferExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class InvalidOfferException
