package auctionPack;


/**
* auction/AuctionPackage/InvalidSellException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

public final class InvalidSellException extends org.omg.CORBA.UserException
{
  public String description = null;

  public InvalidSellException ()
  {
    super(InvalidSellExceptionHelper.id());
  } // ctor

  public InvalidSellException (String _description)
  {
    super(InvalidSellExceptionHelper.id());
    description = _description;
  } // ctor


  public InvalidSellException (String $reason, String _description)
  {
    super(InvalidSellExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class InvalidSellException
