package auctionPack;

/**
* auction/AuctionPackage/InvalidStatusExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

public final class InvalidStatusExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public auctionPack.InvalidStatusException value = null;

  public InvalidStatusExceptionHolder ()
  {
  }

  public InvalidStatusExceptionHolder (auctionPack.InvalidStatusException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = auctionPack.InvalidStatusExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        auctionPack.InvalidStatusExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return auctionPack.InvalidStatusExceptionHelper.type ();
  }

}
