package auctionPack;

/**
* auction/AuctionPackage/InvalidOfferExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

public final class InvalidOfferExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public auctionPack.InvalidOfferException value = null;

  public InvalidOfferExceptionHolder ()
  {
  }

  public InvalidOfferExceptionHolder (auctionPack.InvalidOfferException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = auctionPack.InvalidOfferExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        auctionPack.InvalidOfferExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return auctionPack.InvalidOfferExceptionHelper.type ();
  }

}
