package auctionPack;


/**
* auction/AuctionPackage/InvalidStatusExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

abstract public class InvalidStatusExceptionHelper
{
  private static String  _id = "IDL:auction/Auction/InvalidStatusException:1.0";

  public static void insert (org.omg.CORBA.Any a, auctionPack.InvalidStatusException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static auctionPack.InvalidStatusException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "description",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (auctionPack.InvalidStatusExceptionHelper.id (), "InvalidStatusException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static auctionPack.InvalidStatusException read (org.omg.CORBA.portable.InputStream istream)
  {
        auctionPack.InvalidStatusException value = new auctionPack.InvalidStatusException ();
    // read and discard the repository ID
    istream.read_string ();
    value.description = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, auctionPack.InvalidStatusException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_string (value.description);
  }

}
