package auctionPack;


/**
* auction/AuctionPackage/StatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Auction.idl
* Wednesday, April 8, 2015 12:02:34 AM CDT
*/

abstract public class StatusHelper
{
  private static String  _id = "IDL:auction/Auction/Status:1.0";

  public static void insert (org.omg.CORBA.Any a, auctionPack.AuctionStatus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static auctionPack.AuctionStatus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = auctionPack.AuctionStatusHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (auctionPack.StatusHelper.id (), "Status", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static auctionPack.AuctionStatus read (org.omg.CORBA.portable.InputStream istream)
  {
        auctionPack.AuctionStatus value = null;
    value = auctionPack.AuctionStatusHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, auctionPack.AuctionStatus value)
  {
        auctionPack.AuctionStatusHelper.write (ostream, value);
  }

}
